language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: Jpax6EZ3MLrSFH7AwDqJ27G1m4/1okaocxrNkRZVuXZW3ZbdMVPo0Ss/bTaf0J26HTo5fsuNx+XqP1UW2CYX6TtsK6scu6YET7SrSUoJKnNDCsshOOnRZe6X2mIJdPxvEnE559X+cN/YJKtuHPfwZaQ2hYgKcuQkKYB07DGsArs=
  app: tweetability
  on:
    repo: tillkahlbrock/tweetability
