development:
  adapter: postgresql
  encoding: utf8
  database: tweetability_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: tweetability_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tweetability_production
  pool: 5
  password:
